
## Please write a project name here
project_name: 

## Please select location from the list: https://learn.microsoft.com/en-us/azure/reliability/regions-list
location:

## Networking
enable_networking: false

## Compute 
enable_compute: false

## Database
enable_database: false

## Storage
enable_storage: true

## Security
enable_security: false

## CI/CD
enable_ci_cd: true
